# Form implementation generated from reading ui file 'c:\Users\Den4e\OneDrive\Desktop\yandex\playerMP3vtoroiVar.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6.QtWidgets import QTableWidget, QAbstractItemView, QCheckBox
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 720))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 #CC5500, stop:0.5 0, stop:1 #CC4000);\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 10, 311, 701))
        self.frame.setStyleSheet("background-color: rgba(255, 255, 255, 20);\n"
"border-radius: 10px;\n"
"border: 1px solid rgba(255,255,255, 20);")
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame1 = QtWidgets.QFrame(parent=self.frame)
        self.frame1.setStyleSheet("color: white;\n"
"font-weight: bold;\n"
"font-size: 14px;")
        self.frame1.setObjectName("frame1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame1)
        self.verticalLayout.setContentsMargins(50, 70, 50, 50)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_loadDir = QtWidgets.QPushButton(parent=self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_loadDir.sizePolicy().hasHeightForWidth())
        self.pushButton_loadDir.setSizePolicy(sizePolicy)
        self.pushButton_loadDir.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_loadDir.setMaximumSize(QtCore.QSize(200, 53))
        self.pushButton_loadDir.setBaseSize(QtCore.QSize(22, 50))
        self.pushButton_loadDir.setStyleSheet("QPushButton{\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size: 14px;\n"
"border: 1px solid rgba(255, 255, 255, 50)\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255, 255, 255, 40)\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgba(255, 255, 255, 70)\n"
"}")
        self.pushButton_loadDir.setObjectName("pushButton_loadDir")
        self.verticalLayout.addWidget(self.pushButton_loadDir)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_2.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size: 14px;\n"
"border: 1px solid rgba(255, 255, 255, 50)\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255, 255, 255, 40)\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgba(255, 255, 255, 70)\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)

        spacerItem = QtWidgets.QSpacerItem(15, 15, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.frame1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(1000, 40))
        self.label_2.setStyleSheet("border-radius: 3px;\n"
"margin-left: 0px;\n"
"background-color: rgba(0, 0, 0, 30);\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size: 10px;\n"
"line-height: 0;")
        self.label_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_2.setLineWidth(1)
        self.label_2.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setIndent(-1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setMinimumSize(QtCore.QSize(50, 50))
        self.label.setMaximumSize(QtCore.QSize(500, 500))
        self.label.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border-radius: 170px;\n"
"border: 1px solid rgba(255, 255, 255, 80);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.verticalFrame.setGeometry(QtCore.QRect(350, 20, 621, 681))
        self.verticalFrame.setStyleSheet("background-color: rgba(255, 255, 255, 20);\n"
"border-radius: 20px;\n"
"border: 1px solid rgba(255, 255, 255, 50);\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(0, 0, 45, 150), stop:0.427447 rgba(0, 0, 0, 150), stop:1 rgba(0, 0, 45, 150));\n"
"\n"
"")
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.verticalFrame)
        self.tableWidget.setMaximumSize(QtCore.QSize(1000, 1000))
        self.tableWidget.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.tableWidget.setStyleSheet("background-color: rgba(0, 0, 0, 150);\n"
"")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setStyleSheet("""
    QTableWidget {
        gridline-color: #232326;  /* Цвет линий сетки для таблицы */
    }
    QHeaderView::section {
        background-color: #232326;
        color: white;
        border: none;
        padding: 0px;
    }
    QTableCornerButton::section { 
        background-color: transparent; border: none; 
    }
    QTableWidget::item:selected {
        background-color: rgba(0, 0, 0, 0.1);  /* Цвет фона выделенной ячейки */
        color: white;  /* Цвет текста выделенной ячейки */
    }
""")
        self.verticalLayout_4.addWidget(self.tableWidget)
        self.time = QtWidgets.QLabel(parent=self.verticalFrame)
        self.time.setMaximumSize(QtCore.QSize(100000, 16777215))
        self.time.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.time.setAutoFillBackground(False)
        self.time.setStyleSheet("QLabel{\n"
"border: none;\n"
"background: none;\n"
"}")
        self.time.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.time.setObjectName("time")
        self.verticalLayout_4.addWidget(self.time)
        self.progresBarTrack = QtWidgets.QSlider(parent=self.verticalFrame)
        self.progresBarTrack.setStyleSheet("QSlider{\n"
"border:none;\n"
"border-radius: 8px;\n"
"background: none;\n"
"height: 16px;\n"
"}\n"
"  QSlider::groove:horizontal {\n"
"                border: 1px solid #999;\n"
"                height: 8px;\n"
"                background: #ddd;\n"
"                border-radius: 10px;\n"
"            }\n"
"            QSlider::sub-page:horizontal {\n"
"                background: rgb(67, 67, 67);  /* Цвет заполненной части */\n"
"                border-radius: 10px;\n"
"            }\n"
"            QSlider::handle:horizontal {\n"
"                background: #ffffff;\n"
"                border: 1px solid #5c5c5c;\n"
"                width: 15px;\n"
"                height: 15px;\n"
"                margin: -5px 0;\n"
"                border-radius: 8px;\n"
"            }\n"
"            QSlider::add-page:horizontal {\n"
"                background: rgba(0, 0, 0, 255); /* Цвет незаполненной части */\n"
"                border-radius: 5px;\n"
"            }")
        self.progresBarTrack.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.progresBarTrack.setObjectName("progresBarTrack")
        self.verticalLayout_4.addWidget(self.progresBarTrack)
        self.horizontalFrame = QtWidgets.QFrame(parent=self.verticalFrame)
        self.horizontalFrame.setMaximumSize(QtCore.QSize(600, 100))
        self.horizontalFrame.setStyleSheet("background-color: rgba(0, 0, 0, 150);\n"
"border-radius: 10px;\n"
"border: 1px solid rgba(255, 255, 255, 80);")
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.check_box = QCheckBox( parent=self.horizontalFrame)
        self.check_box.setChecked(False)
        self.horizontalLayout.addWidget(self.check_box)
        self.check_box.setMaximumWidth(15)
        self.check_box.setStyleSheet("""

    QCheckBox::indicator {
        width: 12px;
        height: 12px;
 

        background: white;
        transition: background-color 0.3s ease;
    }
    QCheckBox::indicator:checked {
        background: #CC2500;
    }
    QCheckBox::indicator:unchecked {
        background: #fff;
    }

""")
        self.prev_button = QtWidgets.QPushButton(parent=self.horizontalFrame)
        self.prev_button.setMinimumSize(QtCore.QSize(0, 50))
        self.prev_button.setMaximumSize(QtCore.QSize(35, 16777215))
        self.prev_button.setStyleSheet("background-color: rgba(0, 0, 0, 0, 0);\n"
"border: 0px;")
        self.prev_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/skip_previous_100dp_E8EAED_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.prev_button.setIcon(icon)
        self.prev_button.setIconSize(QtCore.QSize(40, 40))
        self.prev_button.setObjectName("prev_button")
        self.horizontalLayout.addWidget(self.prev_button)
        self.pause_stop_button = QtWidgets.QPushButton(parent=self.horizontalFrame)
        self.pause_stop_button.setMaximumSize(QtCore.QSize(35, 16777215))
        self.pause_stop_button.setStyleSheet("border: 0px;background-color: rgba(0, 0, 0, 0);")
        self.pause_stop_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/play_pause_100dp_E8EAED_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pause_stop_button.setIcon(icon1)
        self.pause_stop_button.setIconSize(QtCore.QSize(40, 40))
        self.pause_stop_button.setObjectName("pause_stop_button")
        self.horizontalLayout.addWidget(self.pause_stop_button)
        self.next_button = QtWidgets.QPushButton(parent=self.horizontalFrame)
        self.next_button.setMaximumSize(QtCore.QSize(35, 16777215))
        self.next_button.setStyleSheet("background-color: rgba(255, 255, 0, 0);\n"
"border: 0px;")
        self.next_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/skip_next_100dp_E8EAED_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.next_button.setIcon(icon2)
        self.next_button.setIconSize(QtCore.QSize(40, 40))
        self.next_button.setObjectName("next_button")
        self.horizontalLayout.addWidget(self.next_button)
        self.verticalSlider = QtWidgets.QSlider(parent=self.horizontalFrame)
        self.verticalSlider.setStyleSheet("QSlider{\n"
"border: none;\n"
"border-radius: 8px;\n"
"background: none;\n"
"width: 10px;\n"
"}\n"
"            QSlider::groove:vertical {\n"
"\n"
"                width: 5px;\n"
"                background: #ddd;\n"
"                border-radius: 3px;\n"
"            }\n"
"            QSlider::sub-page:vertical {\n"
"                background: rgb(255, 255, 255); /* Цвет заполненной части */\n"
"                border-radius: 5px;\n"
"            }\n"
"            QSlider::handle:vertical {\n"
"                background: #ffffff;\n"
"                border: 1px solid #5c5c5c;\n"
"                width: 20px;\n"
"                height: 10px;\n"
"                margin: 0 -5px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QSlider::add-page:vertical {\n"
"                background: #ccc; /* Цвет незаполненной части */\n"
"                border-radius: 5px;\n"
"            }\n"
"        ")
        self.verticalSlider.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.horizontalLayout.addWidget(self.verticalSlider)
        self.verticalLayout_4.addWidget(self.horizontalFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_loadDir.setText(_translate("MainWindow", "Выберать папку"))
        self.pushButton_2.setText(_translate("MainWindow", "Викторина"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"icon/arrow_or_edge_23dp_E8EAED_FILL0_wght200_GRAD0_opsz24.svg\"/></p></body></html>"))
        self.time.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">00:00 / 00:00</span></p></body></html>"))
