# Form implementation generated from reading ui file 'c:\Users\Den4e\OneDrive\Desktop\yandex\viktorina.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(543, 395)
        Form.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0  #CC2500, stop:0.427447  0\n"
", stop:1  #CC2500);")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setMinimumSize(QtCore.QSize(200, 50))
        
        self.pushButton.setStyleSheet("\n"
"QPushButton::pressed {\n"
"background-color: rgba(255, 255, 255, 150)\n"
"}\n"
"QPushButton{\n"
"background: rgba(255, 255, 255, 100);\n"
"border: 1px solid white;\n"
"border-radius: 10px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setMaximumSize(QtCore.QSize(300, 350))
        self.label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label.setStyleSheet("background: rgba(255, 255, 0, 0);\n"
"text-colour: white;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignCenter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setWhatsThis(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600; color:#ffffff;\">Начать</span></p></body></html>"))
        self.pushButton.setText(_translate("Form", "Начать"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">Викторина</span></p></body></html>"))
